fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "sandradelaporte@gmail.com"
        sender_name: "sandradelaporte@gmail.com"
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true
