fos_user_accueil:
    path: /
    controller: App\Controller\SecurityController::loginAction

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    path: /
#    controller: App\Controller\DefaultController::index
