fos_user_accueil:
    path: /
    controller: App\Controller\bundles\FOSUserBundle\SecurityController::loginAction

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

test:
    path: /test
    controller: App\Controller\bundles\FOSUserBundle\SecurityController::testAction
